# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt28th-iOS-Assignment1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sopt28th-iOS-Assignment1
  pod 'Alamofire', '~> 5.2'
end
